name: fire_trade_app
description: AI Amplified Trading

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  requests: ^3.0.1
  http: ^0.12.0+2
  flutter_multiselect: 0.0.1

  # Firebase
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+6

  # Stripe
  stripe_payment: ^1.0.5

  # Razorpay
  razorpay_flutter: ^1.1.2

  fluttertoast: ^3.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^0.5.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
